version: '3.7'

services:
  web:
    build: .
    command: python /usr/src/forum_django/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/forum_django
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
