# Generated by Django 3.0.8 on 2020-09-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200830_0303'),
        ('forum', '0006_auto_20200904_0136'),
    ]

    operations = [
    ]
